# Generated by Django 5.0 on 2024-01-23 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_addcat_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcat',
            old_name='image',
            new_name='images',
        ),
    ]
