# Generated by Django 5.0 on 2024-01-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_rename_image_addcat_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmov',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
